[package]
name = "simple-http-server"
version = "0.1.0"
authors = ["Jackson Carter <kovalsk_syogun@tutamail.com>"]
edition = "2018"

[dependencies]
tokio = { version = "1", features = ["full"] }
warp = "0.3"
